tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/science"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "railwaycat/emacsmacport"

brew "aspell"
brew "chunkwm"
brew "dep"
brew "exercism"
brew "ext2fuse"
brew "git"
brew "glide"
brew "go"
brew "heroku"
brew "hub"
brew "libbtbb"
brew "libpcap"
brew "libusb"
brew "mas"
brew "mpv"
brew "nmap"
brew "node"
brew "opencv"
brew "opencv3"
brew "openssl"
brew "pkg-config"
brew "python3"
brew "readline"
brew "ruby"
brew "ruby-build"
brew "skhd"
brew "socat"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yabai"

cask "alfred"
cask "docker"
cask "eagle"
cask "emacs"
cask "icons8"
cask "iterm2"
cask "java"
cask "kindle"
cask "licecap"
cask "osxfuse"
cask "virtualbox"
cask "vlc"
cask "wireshark"
cask "xquartz"

mas "123D Design", id: 566042322
mas "123DMake", id: 515318186
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
