#!/bin/bash

#
# this script enforces that all vim plugins and configurations be managed using
# this dotfiles package.
# 
# it deletes all vim configuration and then performs an fresh install (immutable
# vim configuration)
#

DOTFILESDIR="${HOME}/.dotfiles"
VIMDIR="${HOME}/.vim"
VIMRC="${HOME}/.vimrc"

NEOVIMDIR="${HOME}/.config/nvim"
NEOVIMRC="${NEOVIMDIR}/init.vim"

#
# remove $VIMDIR if it exists
#
remove_vim_tree(){
    if [ -d "$VIMDIR" ]; then
        rm -rf $VIMDIR
    fi
}

#
# create $VIMDIR and bundle directory
#
create_vim_tree(){
    echo -n "Creating vim tree..."
    mkdir -p ${VIMDIR}/bundle
    echo "done!"
}

#
# clone Vundle, Vim's package/plugin manager
#
install_vundle(){
    echo -n "Installing Vundle..."
    git clone https://github.com/VundleVim/Vundle.vim.git \
      ${VIMDIR}/bundle/Vundle.vim

    echo "done!"
}

#
# setup vimrc by loading the dotfiles vimrc and then running Vundle's install
# command
#
setup_vimrc(){
    echo -n "Linking dotfiles vimrc..."
    echo "so ${DOTFILESDIR}/vimrc" > ${VIMRC}
    echo "done!"

    echo -n "Installing plugins with Vundle..."
    vim +PluginInstall +qall
    echo "done!"
}

#
# support neovim
#
setup_neovim(){	
    echo -n "Setting up neovim to load vimrc..."
    mkdir -p ${NEOVIMDIR}
    echo "set runtimepath^=~/.vim runtimepath+=~/.vim/after" > ${NEOVIMRC}
    echo "let &packpath = &runtimepath" >> ${NEOVIMRC}
    echo "source ~/.vimrc" >> ${NEOVIMRC}
    echo "done!"
}

remove_vim_tree && \
    create_vim_tree && \
    install_vundle && \
    setup_vimrc && \
    setup_neovim
