#!/bin/bash
# setup dotfiles

DOTFILESDIR="${HOME}/.dotfiles"
ZSHRC="${HOME}/.zshrc"

echo -n "Sourcing dotfiles zshrc..."
echo "source ${DOTFILESDIR}/zshrc" > ${ZSHRC}
echo "done!"

# TODO setup zsh and switch over, along with aliases and whatnot

echo -n "Copying gitconfig..."
cp ${DOTFILESDIR}/gitconfig ${HOME}/.gitconfig
echo "done!"
