#!/bin/bash
# setup dotfiles

DOTFILESDIR="${HOME}/.dotfiles"

echo -n "Sourcing dotfiles zshrc..."
echo "source ${DOTFILESDIR}/zshrc" > ${HOME}/.zshrc
echo "done!"

echo -n "Copying gitconfig..."
cp ${DOTFILESDIR}/gitconfig ${HOME}/.gitconfig
echo "done!"
