#!/bin/bash
# setup dotfiles

DOTFILESDIR="${HOME}/.dotfiles"
ZSHRC="${HOME}/.zshrc"
ZSH="${HOME}/.oh-my-zsh"

#
# install oh my zsh
#
if [ -d "$ZSH" ];then
    echo -n "Installing oh-my-zsh..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    echo "done!"
fi

#
# install zsh
#
echo -n "Installing zsh..."
brew install zsh
echo "done!"

#
# change shell to zsh
#
echo -n "Setting zsh as default shell..."
chsh -s /usr/local/bin/zsh
echo "done!"

#
# set up zshrc
#
echo -n "Sourcing dotfiles zshrc..."
echo "source ${DOTFILESDIR}/zshrc" > ${ZSHRC}
echo "done!"

#
# copy Brewfile over
#
echo -n "Copying Brewfile to $HOME..."
cp $DOTFILESDIR/Brewfile ${HOME}/.Brewfile
echo "done!"
