#!/bin/sh
#
#
# berry window manager configuration
# https://berrywm.org/configuration.html
#
#

# decoration geometry
berryc border_width 1
berryc title_height 30

# decoration colors
# 
berryc focus_color   0xFFFFAAFF     # plan9's DPaleYellow
berryc unfocus_color 0x9EEEEEFF     # plan9's DPalegreygreen
berryc text_focus_color   0X000000FF  # plan9's DBlack
berryc text_unfocus_color 0x000000FF  

# settings
berryc draw_text   "true"
berryc smart_place "true"


